"""reset_schema

Revision ID: 33d2aca9a36c
Revises: 
Create Date: 2026-01-08 10:30:53.870508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '33d2aca9a36c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False, comment='관리/검색용 이메일 스냅샷'),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=True),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('liked_project_ids', sa.JSON(), nullable=True, comment='Array: [1, 20, 55]'),
    sa.Column('test_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='📝 프로필 수정 일시'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_stacks',
    sa.Column('stack_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='🔑 PK'),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('position_type', sa.Enum('FRONTEND', 'BACKEND', 'DB', 'INFRA', 'DESIGN', 'ETC', name='stackcategory'), nullable=False),
    sa.Column('stack_name', sa.Enum('React', 'Vue', 'Nextjs', 'Svelte', 'Angular', 'TypeScript', 'JavaScript', 'TailwindCSS', 'StyledComponents', 'Redux', 'Recoil', 'Vite', 'Webpack', 'Java', 'Spring', 'Nodejs', 'Nestjs', 'Go', 'Python', 'Django', 'Flask', 'Express', 'php', 'Laravel', 'GraphQL', 'RubyOnRails', 'CSharp', 'DotNET', 'MySQL', 'PostgreSQL', 'MongoDB', 'Redis', 'Oracle', 'SQLite', 'MariaDB', 'Cassandra', 'DynamoDB', 'FirebaseFirestore', 'Prisma', 'AWS', 'Docker', 'Kubernetes', 'GCP', 'Azure', 'Terraform', 'Jenkins', 'GithubActions', 'Nginx', 'Linux', 'Vercel', 'Netlify', 'Figma', 'AdobeXD', 'Sketch', 'Canva', 'Photoshop', 'Illustrator', 'Blender', 'UIUX_Design', 'Branding', 'Git', 'Slack', 'Jira', 'Notion', 'Discord', 'Postman', 'Swagger', 'Zeplin', name='techstack'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stack_id')
    )
    op.create_index(op.f('ix_user_stacks_user_id'), 'user_stacks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stacks_user_id'), table_name='user_stacks')
    op.drop_table('user_stacks')
    op.drop_table('users')
    # ### end Alembic commands ###
