"""reset_schema

Revision ID: 876cda061eb9
Revises: 33d2aca9a36c
Create Date: 2026-01-08 10:54:07.364349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '876cda061eb9'
down_revision: Union[str, Sequence[str], None] = '33d2aca9a36c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_stacks', 'stack_id',
               existing_type=mysql.BIGINT(),
               comment='🔑 PK',
               existing_comment='? PK',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='📝 프로필 수정 일시',
               existing_comment='? 프로필 수정 일시',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='? 프로필 수정 일시',
               existing_comment='📝 프로필 수정 일시',
               existing_nullable=True)
    op.alter_column('user_stacks', 'stack_id',
               existing_type=mysql.BIGINT(),
               comment='? PK',
               existing_comment='🔑 PK',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
